add options to proj_conv and make all_lrelu default in the definition of SPADEMaskerDecoder
cc-ai/omnigan pull request #187
Opened 2021-01-20 00:29 UTC by tianyu-z

2021-01-24 20:59 UTC, vict0rsch requested changes

2021-01-24 20:59 UTC, vict0rsch commented on omnigan/blocks.py
> +            return out
need to have an `else` which raises a NotImplementedError

2021-01-24 20:59 UTC, vict0rsch commented on omnigan/generator.py
> +                num_proj = self.opts.gen.m.proj_dim
`proj_dim` is a better name for that variable, more obvious

2021-01-25 18:37 UTC, tianyu-z commented
I fixed them but I am doing some other experiments. I would like to keep this PR as a draft now. Will let you know when my other exps are done.

2021-01-25 22:39 UTC, vict0rsch commented
Cool thanks :)

2021-02-01 07:22 UTC, tianyu-z commented
What this PR does:
Add options to backprop conditions for the maskSPADEdecoder and also add options for proj_conv and all_lrelu as the activation functions.

Conclusion (bs=5):
1. Training Speed(Without Backprop) = 758.1 step/hr; Training Speeing(With Backprop) = 638.79 step/hr. 
2. Use_proj does help overall. But proj_dim = 64 does not have much difference with proj_dim = 128.
3. Models without Backprop get reasonable result on Mask at epoch = 7 and Models with Backprop get reasonable result on Mask at epoch = 5. But after epoch 15, they perform similar in the result of the Masker. ([Comparision exps](https://www.comet.ml/tianyu-z/omnigan/dc81d1f10c1b44ebb6a0b0548f49164e/8bc4c25f34fb44db8b403d0b2bde77e0/compare?experiment-tab=images&groupBy=false&orderBy=asc&search=val_r_m_%5B0-9%5D%2A_%230&searchType=regex&sortBy=step))

2021-02-07 01:47 UTC, tianyu-z commented
@vict0rsch I retrained the models. From my viewpoint, the conclusion above still holds:
[use_proj+backprop](https://www.comet.ml/tianyu-z/omnigan/b659c2e62ff2468191898c44d54ec81c?experiment-tab=images&groupBy=false&orderBy=asc&search=val_r_m_%5B0-9%5D%2A_%233&searchType=regex&sortBy=step
)
[backprop](https://www.comet.ml/tianyu-z/omnigan/d48821d41c124373a24b6f241e5e6ad2?experiment-tab=images&groupBy=false&orderBy=desc&search=val_r_m_%5B0-9%5D%2A_%231&searchType=regex&sortBy=step
)
[use_proj](https://www.comet.ml/tianyu-z/omnigan/2562a3588f494bf3a758f805c252e25d?experiment-tab=images&groupBy=false&orderBy=asc&search=val_r_m_%5B0-9%5D%2A_%233&searchType=regex&sortBy=step
)
One more thing that I noticed:
models with proj layer tend to flood more:
![image](https://user-images.githubusercontent.com/53099276/107133994-07dd0e00-68bc-11eb-824b-4832ecfa0fc4.png)
in an extreme case, no one survives: 
![image](https://user-images.githubusercontent.com/53099276/107134010-38bd4300-68bc-11eb-9752-72fb0661a96b.png)

models without proj layer tend to flood less:
![image](https://user-images.githubusercontent.com/53099276/107134001-1f1bfb80-68bc-11eb-9c23-00d72b0b31ab.png)
in an extreme case, people almost are not flooded:
![image](https://user-images.githubusercontent.com/53099276/107134048-846fec80-68bc-11eb-9439-45917866de83.png)

2021-02-09 14:26 UTC, merged